### ISSUE TITLE
Bewertung ändern im New-Rating-Konzept

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#100]
Der Overall-Score (letzter Slider) updated sich nicht und der neue Wert wird bei einer Bearbeitung nicht übernommen.

(Außerdem werden die Werte von Mündlich/Schriftlich nicht zurückgesetzt, wenn man die Prüfungsart zu Sonstiges ändert. Das ist aber denke ich nicht super prioritär.)

**Comment by juliangermek** [comment]
Overall-Score ist gefixt.
Das andere hab ich auch mal überlegt, bin aber zu dem Schluss gekommen, dass das eigentlich nicht nötig bzw. vielleicht sogar unerwünscht ist. Meinst du, das sollte implementiert werden?

**Comment by jonas-l-b** [comment]
Ne lass lieber. Unnötiger Aufwand.
