### ISSUE TITLE
Suchfunktion new-rating-concept anpassen

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#102]

**Comment by juliangermek** [comment]
Erste Version steht, siehe branch ergebnistabelle. Habe zwar ein bisschen rumgetestet, aber bug-free ists wahrscheinlich nicht ganz. Die Darstellung derSortierung nach Reproduktion/Transfer bzw. Quali/Quanti steht evtl. noch zur Debatte.
@jonas-l-b

**Comment by jonas-l-b** [comment]
Reproduktion/Transfer Quali/Quanti-Vorschlag: 
Statt negativen Zahlen, die Werte manipulieren, dass Sie in diesen Fällen umgekehrt werden. (Es ist halt unintuitiv, dass -10 das höchste sein soll.)
Ansonsten gut. Hab auch keine Bugs gefunden. (Aber auch aus Mangel an Daten, das ergibt sich bestimmt noch.

**Comment by juliangermek** [comment]
Guter Vorschlag, habe ein neues Issue dazu aufgemacht (weil ich glaube ich dieses über fixed geschlossen hab? (Wird das ausgeführt, wenn was in den master gemergt wird?)). Ansonsten erstmal zurückgestellt wegen lange Nacht des Wissens Vorbereitung.
