### ISSUE TITLE
Multi Search Selection Admin

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#106]
@jonas-l-b , sowas hier ("Multi Search Selection") sieht ziemlich gut aus: https://semantic-ui.com/modules/dropdown.html

Ich weiß bloß nicht so ganz, wie das integriert wird; anscheinend kann man das über einen 'package manager' installieren? Oder doch lieber am besten selber versuchen, die einzelnen Dateien einzufügen?

**Comment by jonas-l-b** [comment]
Ich hab npm schon installiert und dir im branch semantic-ui mal semantic-ui installiert. du findest die gebuildeten dateien unter semantic/dist/
(Da findest du auch die einzelnen komponenten. wenn du nur das dropdown benutzt, vielleicht als einzelne komponente einbinden.

**Comment by jonas-l-b** [comment]
(BTW: Das pusht unsere Code Statistik so richtig 😆 )

**Comment by jonas-l-b** [comment]
Beachte auch: Wenn du die Components nicht einzeln verwendest, weiß ich nicht ob sich semantic ui möglicherweise mit bootstrap kloppt

**Comment by jonas-l-b** [comment]
Hab schon angefangen es zu implementieren, gibt leider noch ein Problem in der HTML Darstellung. Aber ansonsten funktionsfähig

**Comment by jonas-l-b** [comment]
Behoben^^
