### ISSUE TITLE
Laden für Search-Box

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#107]
Da das jetzt ja doch bissl länger dauert wäre der loader nicht schlecht

**Comment by jonas-l-b** [comment]
Ich warte mal bis das auf dem Server läuft. Aber länger als 1sek darf es auf keinen fall dauern (und tut es leider aktuell teilweise)

**Comment by jonas-l-b** [comment]
Caching auf dem Server ist sexy smart und schnell. Loader glaube ich nicht notwendig.
