### ISSUE TITLE
Twig Probleme auf Server

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#115]
Will man eine Veranstaltung (auf dem Server) bewerten, bekommt man:
![image](https://user-images.githubusercontent.com/30285755/32546649-eb334f56-c4d3-11e7-990d-c788b12d2047.png)
Habe eine Bewertung direkt in die DB eingetragen und bekomme in der comment section
![image](https://user-images.githubusercontent.com/30285755/32546686-ffcdb686-c4d3-11e7-8f7f-1f54df165c69.png)

Ich werde da direkt ehrlich gesagt nicht so draus schlau; habe den vendor-Ordner versuchshalber nochmal rübergezogen, bekomme aber keine Besserung.

Hast du eine Idee, @jonas-l-b?

(Habe ansonsten kleine Änderungen und bugfixes (da war irgendwie ganz schön viel kaputt, größtenteils wegen der Eliminierung von subject.code) vorgenommen, die ich alle direkt in den master gemergt hab. Hoffe das passt!)

**Comment by jonas-l-b** [comment]
Ok ich kümmer mich da noch vor morgen Abend drum. Weiß nicht was da schiefgegangen ist.

Danke für die Bugfixes. Klar passt das ich merge aktuell auch nur in den master, wir haben ja nicht mehr so viel in der pipeline wie früher ;P

**Comment by jonas-l-b** [comment]
(Jup das war der Fehler. Achtung: Der Fehler ist nur weg, wenn du den Studienführer über studienführer.vwi-karlsruhe.de aufrufst - die URL triggert php 7)

**Comment by jonas-l-b** [comment]
wir hatten das übrigens schonmal bei dir damals. 

Twig meckert eigentlich wenn man es installiert und PHP nicht 7 oder höher ist, aber ich hatte es ja bei mir installiert und du hattest nur die kopie davon und dann meckert es nicht mehr 🤦‍♂️
