### ISSUE TITLE
DirectoryIndex

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#117]
Muss noch geändert werden, sonst kommt quatsch dabei raus, wenn man nur studienführer.vwi-karlsruhe.de eingibt.
DirectoryIndex tree.php muss glaube ich in .htaccess, allerdings scheit das erstmal nur zu funktionieren, wenn man bereits eine session hat. Vielleicht löst sich das auch einfach mit DirectoryIndex login.php (noch nicht getestet). Könnte auch mit dem redirect dass man bspw. ohne session aber mit cookie studienführer.vwi-karlsruhe.de/admin.php eingibt und dann auch dahin gelagt) zusammenhängen, muss man mal ordentlich untersuchen....

**Comment by juliangermek** [comment]
Hab ich auch schon überlegt, ist vielleicht gar nicht schlecht so. Funktioniert gut, wenn man bereits eine session gestartet hat

Re-open: Wenn man nur studienführer.vwi-karlsruhe.de eingibt und einen cookie hat, kommt man auf 404. Das hat wohl damit zu tun, dass die url vor dem redirect in der url als variable gespeichert wird und im Moment mit basename() der relevante Teil rausgeschnitten wird (und das bei nur studienführer.vwi-karlsruhe.de Quatsch ergibt).

**Comment by jonas-l-b** [comment]
Ah ok. Nicht bedacht.

Guten morgen Julian, wir sitzen noch dran. Zu 5 gestartet, schnell zu vier geworden und jetzt tapfer zu dritt kämpfen wir uns durch den Rest des Bachelors. Es gibt noch viele Fehler und ungereimtheiten. (Und nur wenig Master.) Wir sollten über heute abend mal skypen wie wir weiter vorgehen. 

PS: Nach über 5 stunden kriegen wir hier die maximal krise...

**Comment by juliangermek** [comment]
Geht nicht:
- studienfuehrer.vwi-karlsruhe.de/admin.php
- studienführer.vwi-karlsruhe.de
- studienfuehrer.vwi-karlsruhe.de
- studienfuehrer.vwi-karlsruhe.de/index.php

Geht:
- studienführer.vwi-karlsruhe.de/admin.php
- studienführer.vwi-karlsruhe.de/index.php

--> Mit studienf**ue**hrer scheint es nie zu klappen, mit studienf**ü**hrer nur, wenn noch was dahinter steht. Es sollte aber alles klappen.
