### ISSUE TITLE
Suchergebnisse auf 20 Maximal beschränken

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#118]
Probiers mal aus. Dann weißt du warum

**Comment by juliangermek** [comment]
Habe schon....

**Comment by jonas-l-b** [comment]
Ist schon krass alleine wie lange der Server mit den DB Requests rechnet - weil die paar kb übertragen dauert daran nicht lange. Jetzt stellen wir uns nochmal 2000 Bewertungen vor, die ja alle für die einzelnen gesamtwertungen ausgewertet werden 😝

**Comment by juliangermek** [comment]
Das hat mich auch etwas gewundert. Hast du dir mal angeschaut, wie diese Tabelle erstellt wird? Können da auch mal drüber schauen, vielleicht ist da ja was dabei, was sehr aufwendig ist...?

Aber ganz grob wird halt nach allen relevanten subjects gesucht, dann wird für jedes Bewertungen abgefragt, dann wird alles in ein Feld gepackt und das wird dann sortiert und ausgegeben. Die Datenbankabfrage enthält 8 JOINs; weiß nicht, ob die dadurch deutlich aufwendiger wird - außerdem ist das eh eigentlich zu umgehen. Bei den Bewertungen könnte man eventuell kürzen und nur das abfragen, was später auch angezeigt wird. Den Sortieralgorithmus habe ich auch nicht auf Laufzeit gecheckt.

Vielleicht gibts auch einen ganz anderen Ansatz, der bspw. alles direkt bei der Abfrage macht, aber das wäre halt alles neu schreiben (falls es denn geht).
