### ISSUE TITLE
Ergebnistabelle layouten

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#12]
Die Ergebnistabelle nach dem Suchen ist sehr vollgepackt, sodass das Layout etwas darunter leidet, bspw. in so einem Fall:
![image](https://user-images.githubusercontent.com/30285755/28967085-e2480ade-795c-11e7-819c-8d1a934e5175.png)

Idee: Größe (bzw. Höhe) der Felder beschränken (hidden overflow) und auf Klick erweitern.

Da einige Anfragen viele Ergebnisse zurückgeben können: Pagination?

**Comment by jonas-l-b** [comment]
Ein rudimentärer Pager ist im branch PagerResultTable implementiert. Hier muss jetzt aber noch wie gesagt die Höhe der Tabellenzeilen fix werden, da es ansonsten eher unschön ist.

**Comment by jonas-l-b** [comment]
Fix in #29
