### ISSUE TITLE
Enhancement: Mehr Features für Admins und Super-Admins

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#120]
Ich habe mir mal überlegt, welche Tools ein Admin/Super-Admin noch so bräuchte, um den Studienführer zu verwalten ohne direkt in die Datenbank zu gehen. Wollte mal hören, was du dazu denkst und ob du noch mehr Vorschläge hast:

Admin:
- Zugriff auf User-Profile (bzw. falls das für jeden mal möglich sein sollte: 'vollen' Zugriff, bspw. auf E-Mail)
- Möglichkeit, einem Nutzer einen Aktivierungslink erneut zu senden (Direkt aktivieren hatte ich auch überlegt. Wäre manchmal sicher einfacher, allerdings geht halt ein bisschen Sicherheit dabei drauf - je nachdem, wer Admin ist. Kompromiss könnte sein, dass man eindringlich gefragt wird, ob man wirklich den Nutzer ohne E-Mail aktivieren will)

Super-Admin:
- Nachrichten löschen. War eigentlich nicht vorgesehen, da die einfach 'Bearbeitet' werden (quasi wie Issues auf Github).
- Kommentare beliebiger Nutzer löschen (irgendwie muss man ja auch unangebrachte Kommentare reagieren können

**Comment by jonas-l-b** [comment]
Zu Admin 1: Finde ich kritisch. Zugriff Read ja, zugriff write nein mMn.
Zu Admin 2: Wie wäre es eher wenn man dem Nutzer den Aktivierungslink erneut schickt, wenn er versucht sich einzuloggen ohne auf den Link geklickt zu haben. Wirkt mMn einfacher.
Zu Super-Admin 1: keine meinung.
Zu super-admin 2: Sehr wichtig und notwendig!

**Comment by juliangermek** [comment]
Admin 1: ja (nur read), siehe Admin-Bereich
Admin 2: ja, siehe Admin Bereich. Außerdem Button auf login.php wenn versucht wird, sich mit nicht aktiviertem Account anzumelden
Super-Admin 1: Ja
Super-Admin 2: Ja
