### ISSUE TITLE
Veranstaltungsverzeichnisbaum initial collapse verhindern

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#20]
Der Veranstaltungsverzeichnisbaum "collapsed" beim laden der Seite zunächst. Mit einem vollen MHB kann das eher unschön aussehen. Wie könnte man das verhindern. Man muss vermutlich etwas knobeln, aber dabei kann man auch viel lernen.

**Comment by juliangermek** [comment]
Das ist bisher mehr oder weniger Absicht und wird durch die Funktion ab Zeile 529 in tree.php verursacht. Löscht man die Funktion, ist das Verzeichnis direkt beim Laden komplett ausgeklappt.
Die Idee dahinter war, weil das Verzeichnis ja ziemlich mächtig sein wird, es am Anfang zugeklappt sein soll.

Ich hab das ehrlich gesagt irgendwie kopiert und jemand hat darunter die Funktion gepostet, weil er das gleiche erreichen wollte - quasi als Umgehung des Problems.

Lass uns mal überlegen, was wir gerne hätten und dann schauen wir, ob das bereits Existente sich dahingehend abändern lässt.

**Comment by jonas-l-b** [comment]
Ich meinte eigentlich nicht, dass es ausgeklappt sein soll. Sondern das die Animation des Einklappens einen Bruchteil einer Sekunde aufploppt.

**Comment by juliangermek** [comment]
Das stimmt, das ist unnötig. Knobeln ist wohl das richtige Label..

**Comment by jonas-l-b** [comment]
War dann doch recht leicht, wenn man es sich genauer anschaut 😆
