### ISSUE TITLE
Mausklicks bei Autosearch falsch/nicht registriert

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#30]
Klicks von der Maus werden bei Autosearch unregelmäßig erkannt. Ich konnte es bisher noch nicht festmachen woran es liegt. In Chrome funktioniert es bei mir gar nicht, bei Edge nur ca. jedes zweite mal. 

Vermutung: Eine Inkompatibilität mit der Bootstrap navbar, aber bisher habe ich keine Ahnung.

**Comment by juliangermek** [comment]
Bei mir funktioniert die Suche ausschließlich, wenn man auf ein vorgeschlagenes Ergebnis klickt. Gibt man einen (vorhandenen) Begriff ein, und bestätigt mit Enter oder klickt auf die Lupe, wird das Suchfeld geleert, aber nichts passiert. Meinst du das?

Noch was anderes: Ist die Ergebnisliste eigentlich zahlenmäßig limitiert? Wenn man später nur einen Buchstaben eingibt, dürfte das ja einige Ergebnisse liefern...

**Comment by jonas-l-b** [comment]
Das ist auch ein interessantes Verhalten. Bei mir wird auf Druck der Enter-Taste der oberste "Match" ausgewählt. Die Suchtaste funktioniert tatsächlich noch nicht wirklich richtig, da bin ich noch dran. 

Zahlenmäßig limitiert ist es ja. Und es wird auch immer mindestens ein Ergebnis aus jeder Kategorie angezeigt, wenn es eins gibt. Aber nie mehr als insgesamt 8 Ergebnisse. Innerhalb einer Kategorie nie mehr als 5. Die Anzahl der Anzeigen ist also dynamisch.
