### ISSUE TITLE
Advanced Search: Kein Anchor nach Suchen

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#32]
Wenn man auf "Filtern & Sortieren" klickt, kommt man wieder ganz oben raus statt direkt bei der Tabelle. Ein einfacher anchor ist hier aber glaube ich schwieriger, weil das ja quasi in diesem Button drin ist.
Kann man das irgendwie umgehen oder muss AJAX her?

(Vielleicht sollten wir aber auch erstmal abwarten, wie wir die Startseite gestalten - vielleicht brauchen wir ja diese beiden Buttons ja gar nicht und das Problem löst sich quasi von selbst...)

**Comment by jonas-l-b** [comment]
Mal grundsätzlich zur Startseitengestaltung. Die Auswahl zwischen rechts und links sollte nicht mit einem Post-Request stattfinden. Beim Neu-Laden der Seite muss man nämlich die Auswahl immer erneut bestätigen. Einfacher wäre ein Link, in dem in der URL der Parameter übergeben wird und wir das ganze per $_GET[] in php abfragen.

**Comment by juliangermek** [comment]
Werde mich bei Gelegenheit mal damit auseinandersetzen, was GET und POST genau bedeutet....
