### ISSUE TITLE
Design-Entscheidung: "Immer neuer Tab?"

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#41]
Aktuell rufen sehr viele Links immer einen neuen Tab auf. Mich irritiert das wenn ich ehrlich bin. @juliangermek hast du dir dabei irgendetwas bestimmtes gedacht?

**Comment by juliangermek** [comment]
Mit Sicherheit, allerdings ist tatsächlich nichts 100 %ig konsistent implementiert.
Bspw. beim Aufruf eines Suchergebnisses habe ich es gerne, wenn eine neue Seite geöffnet wird. Können gerne mal eine Guideline für wann neue Tabs geöffnet werden sollen festlegen.

**Comment by juliangermek** [comment]
Hab das teilweise wieder rausgenommen und es etwas mehr vereinheitlicht. Werde mir bei Gelegeneheit da mal was zu überlegen.
