### ISSUE TITLE
Admin-Bereich: Suchfunktion bei Auswahlen hinzufügen

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#43]
zB hier:
![image](https://user-images.githubusercontent.com/30285755/29248101-675d00de-8052-11e7-8a14-53e66ccb8267.png)

**Comment by jonas-l-b** [comment]
Hiermit sollte es leicht gehen: https://github.com/danielfarrell/bootstrap-combobox

Beachte das "Inline-Form" Beispiel hier http://bootstrap-combobox-test.herokuapp.com/ . Das wäre für uns glaube ich am besten
