### ISSUE TITLE
Up for discussion: Bei Kommentaren Titel entfernen

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#44]
Titel eingeben ist irgendwie nervig..

**Comment by jonas-l-b** [comment]
Titel bin ich auch kein Riesenfan von. Ist halt wie bei Amazon, aber schon da stellt sich immer die Frage was man eigentlich eintragen soll.

Generell bei den Kommentare: 

Eine Anleitung/ein Vorschlag was wir hören wollen wäre vielleich nicht schlecht. Wenn es schon im Textfeld steht oder als Infoknopf oder ähnlichem. alla "Was war deine Erfahrung?", "Was möchtest du Teilnehmern dieser Veranstaltung mit auf den Weg geben?" oder ähnlichem ;)

Generell wäre es auch nice, wenn man seine bewertung später ändern könnte (vielleicht neuer issue)
