### ISSUE TITLE
Aus Gründen steht bei schon bewerteten Veranstaltungen "Vielen Dank" irgendwo rum...

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#47]
![image](https://user-images.githubusercontent.com/30285755/29250337-331fc086-8084-11e7-8d60-c338a22695c9.png)

**Comment by jonas-l-b** [comment]
Das wird wohl mein Fehler sein. 

Schau mir mal an, was ich da falsch gemacht habe. Sollte bei allen stehen, die die Veranstaltungen schon bewertet haben, damit der Button halt verschwindet.

**Comment by juliangermek** [comment]
Das passt glaub ich schon. man konnte aber auch davor schon nicht mehrfach bewerten - da stand es dann im Modal wenn man auf den Button geklickt hat. Deine Variante ist aber auch nicht schlecht, wollen wir lieber die nehmen?

**Comment by jonas-l-b** [comment]
Das hab ich gesehen, aber ich wollte das der Button verschwindet. Wenn du den aber jetzt durch einen "editieren"-Button ersetzt wäre das auch ok. Bin da neutral eingestellt, mach mal wie du es für richtig hältst ;)
