### ISSUE TITLE
Auch mit username anmelden können/Eingeloggt bleiben

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#5]
Title says it all

**Comment by jonas-l-b** [comment]
Man kann ja gleich auch die Möglichkeit schaffen, immer eingeloggt zu bleiben. Die aktuelle Session-Länge ist ziemlich lang aber wenn ich mich nicht irre endet sie nach einiger Zeit, oder? @juliangermek 

Kleine Liste:
- [ ] Eingeloggt bleiben
- [ ] Auch mit username anmelden können

**Comment by juliangermek** [comment]
Weiß ich ehrlich gesagt nicht, müsste man mal nachschauen. Bisher ist die Session glaube ich beendet, wenn man das Fenster schließt (ist das der default?).

**Comment by juliangermek** [comment]
Nochmal zum eingeloggt bleiben:
Der approach ist anscheinend, dass man einen cookie erzeugt, der einen random hash enthält (keine Benutzerdaten). Den kann man dann beim Login nutzen, um den Nutzer zu identifizieren.
(zb hier: https://stackoverflow.com/questions/1354999/keep-me-logged-in-the-best-approach)

Allerdings könnte man doch einfach den cookie jemanden anders geben, der sich dann damit "einloggt". Ist das nicht ein ziemliches security-Problem?

**Comment by juliangermek** [comment]
Push ;)

Meinst du, das mit den cookies passt? Weil dann würde ich das mal probieren...

**Comment by jonas-l-b** [comment]
Antwort kommt noch heute 🙈

**Comment by jonas-l-b** [comment]
Also zum einen ist das kein Security Problem. Wenn ich dir meinen Cookie gebe, ist das so wie wenn ich dir mein Passwort gebe. Wenn du dich damit einloggst bin ich selbst schuld.

Der approach passt so. Ich finde diese Antwort noch ganz gut runtergebrochen: https://stackoverflow.com/a/244907/6843456 Der series identifier ist in dem Fall nämlich auch nicht die user_id. Aber im groben sagen die alle das gleiche. 

Wenn du Lust hast den Ball aus dem Park zu hauen 👅, dann kannst du dir den Branch: loginZendAuthentication ansehen. Der ist auf dem Stand von serverTest und außerdem sind zwei Komponenten des Zend Frameworks installiert. Und zwar das Session Component und das Authentication Component. 
https://docs.zendframework.com/zend-authentication/
https://docs.zendframework.com/zend-session/
Mit diesen Komponenten kann man ein ziemlich vernünftiges Authentication Verfahren implementieren, dass sich dann auch um Aspekte wie CSRF und ähnliches kümmert. Ein mMn vernünftig aussehendes Tutorial gäbe es hier: 
https://olegkrivtsov.github.io/using-zend-framework-3-book/html/en/User_Management__Authentication_and_Access_Filtering/Implementing_User_Authentication.html
Findet man aber noch mehr zu. Bei google hilft die Zeiteinschränkung "Letztes Jahr".

Nur leider ist die Remember Me Lösung von Zend ziemlich unbefriediegend, also das müsste man doch noch selber wie oben gegeben machen. 

Kannst dich auch einfach nur um Remember Me kümmern und ich implementier das mal wann anders. Aber wenn du Lust hast ;)

(Übrigens könnte man - ist aber etwas off-topic - benutzergruppenmanagement auch gut via https://zendframework.github.io/zend-permissions-acl/ oder https://zendframework.github.io/zend-permissions-rbac/ lösen.)

Diese ganzen Komponenten brauchen wir nicht zwingend. Aber sie sind idR gut programmiert und lösen das Problem auf hohem Standard. Außerdem kann man sie später leicht updaten und sie strukturieren das Projekt sinnvoll, damit man es leicht erweitern und ausbauen kann. Aber wie gesagt, wir können auch alles selber machen ;) Ist nur ein Denkanstoß 😛
