### ISSUE TITLE
Kommentare doppelt bewerten

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#52]
Wenn man ganz schnell klickt, kann man Kommentare doppelt bewerten, bevor man daran gehindert wird.

**Comment by juliangermek** [comment]
Na da hast du dich gefreut, wie du das gefunden hast, oder :P?
Werde mir es bei Gelegenheit mal anschauen....

**Comment by juliangermek** [comment]
Habe es probiert mit
```
var isRunning = false;
if(isRunning==false){
	function colorChange(id) {
	isRunning = true;
	...
	isRunning = false;
	}
}
```
Leider ohne Erfolg...
Habe es auch mal jQuery angeschaut, scheint echt ne coole Sache zu sein! Allerdings krieg ich das jetzt nicht mal eben umgemodelt....

**Comment by jonas-l-b** [comment]
Ich schau es mir am WE mal an

**Comment by jonas-l-b** [comment]
Recht simpel, du hast falsch geklammert:

![image](https://user-images.githubusercontent.com/12882702/29372329-148acdcc-82ab-11e7-8975-1803af94e4a2.png)
