### ISSUE TITLE
Kontakt User - Admin

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#57]
Für Fehler, Feedback, Fragen, ... sollte der user die Möglichkeit haben, mit uns in Kontakt zu treten.
Frage: Wie Nachrichten verwalten? (Einfach an bestimmte E-Mail schicken, Direkt in die db speichern, im Admin-Bereich was dazu aufsetzen und Benachrichtigungsmail verschicken? Letzteres stelle ich mir gerade gar nicht so schlecht vor)

- [ ] Kontaktformular (für alle Anfragen)
- [ ] Kommentar melden (z.B. wegen unangebrachter Sprache, ...)
- [ ] Fehler/Veränderung melden (in Veranstaltung, ...)
- [ ] Feedback-Button (wohin genau)?

Denke, da kann man auch mal ein bisschen brainstormen; hab doch auch mal was ins Podio dazu gestellt.

**Comment by juliangermek** [comment]
@jonas-l-b , wäre "Feedback geben" eigentlich ein Beispiel, wann ein Service sinnvoll sein kann? Man könnte dem Service ein paar Infos wie Feedbacktyp (Fehler, Feedback, Frage, ...), user_id, zeitpunkt, ... mitgeben und er packt sie dann in die Datenbank und schreibt Mails an alle Admins, die in einer Liste stehen.

**Comment by jonas-l-b** [comment]
Schon ja. Ist auf jeden Fall ein größerer Aufgabenbereich, der inhaltlich gut gebündelt werden kann. So ein FeedbackService könnte sich auch um gemeldete Kommentare kümmern o.ä.

**Comment by juliangermek** [comment]
Ich habe mal ein grobes Konzept erstellt, was man so machen könnte (in Beschreibung): https://podio.com/estiem/vwi-estiem-karlsruhe-allgemein/apps/studienfuhrer/items/17

Was meinst du @jonas-l-b dazu? Falls du das in die Richtung befürwortest: Meinst du, es gibt Teile, die wir nicht selber entwickeln müssen, weil sie schon gut existieren?

**Comment by jonas-l-b** [comment]
Ich hab mal rumgeschaut, aber spontan nix bestimmtes gefunden. Wahrscheinlich kann man kleinere Komponenten wieder ganz gut zusammenwürfeln.
