### ISSUE TITLE
User-Profil: Menü

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#58]
Hatte eben überlegt, wie wir das Benutzerprofil gestalten wollen und dachte dabei an ein kleines Menü mit Daten, Favoriten, ...
Jetzt allerdings die Frage, wie das technisch am besten gelöst werden könnte: Mit javascript verschiedene Bereiche der php-Datei zeigen und verstecken und via Links verschiedene php-Dateien verknüpfen. Letzteres hätte eventuell den Vorteil, dass man dann Links zu den Unterseiten hat.

**Comment by jonas-l-b** [comment]
Ich wäre für Bootstrap Tabs mit sharebarem Link. 

Bootstrap tabs siehe hier: https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp
Den Link sharebar machen siehe die antwort hier: https://stackoverflow.com/a/10787789/6843456
