### ISSUE TITLE
Prozentanzeige Zählweise

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#59]
Eigentlich ergibt es gar keinen sinn, dass 1 Stern 14% sind. Ich finde irgendwie, das sollten 0 Prozent sein, oder? 

![image](https://user-images.githubusercontent.com/12882702/29369678-94e8de76-82a3-11e7-8f7e-6ba610963542.png)

**Comment by juliangermek** [comment]
Hast du wohl recht; ich wollte aber mal abwarten, bis wir uns auf Kriterien geeignet haben, bevor es hier weitergeht. Riecht sonst nach viel unnötiger Arbeit!

**Comment by juliangermek** [comment]
Closed. Hat sich eh erledigt.
