### ISSUE TITLE
Kommentare löschen und ändern ist auskommentiert

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#67]
Nach Diskussion Code löschen oder wieder aktivieren.

**Comment by jonas-l-b** [comment]
Hab es wieder aktiviert, weil ich die Funktion weiterentwickelt habe. (Bin auch stark dafür, dass wir diese Funktionalität grundsätzlich haben. Inwiefern das mit den Up/Down-Votes funktioniert ist mir nach einigem nachdenken eigentlich wumme)

**Comment by jonas-l-b** [comment]
Außerdem ist das kommentare löschen sau praktisch beim testen 😆
