### ISSUE TITLE
Passwort ändern

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#7]
Über einen Klick auf den Benutzernamen rechts oben kann man sein Profil aufrufen. Dort gibt es die Möglichkeit, sein Passwort zu ändern. Bitte testen!
(Ich habe mal ein "test" Label zugefügt - Ich denke, dass es bei neuen Features ganz gut wäre, wenn sie auch mal jemand anders testet. Meinungen?)

**Comment by jonas-l-b** [comment]
Hab das Label leicht angepasst und auch noch ein "testing"-Label hinzugefügt. Das eine ist aktiv, das andere passiv. Ich finde das kann Verwirrung vermeiden. :)

**Comment by jonas-l-b** [comment]
Im Branch generalFormatImprovements arbeite ich gerade daran einen PHPMailer zu implementieren. Dieser arbeitet verlässlicher als die mail-Methode in PHP und bietet viele weitere Features. Ich implementiere ihn in einem Singleton-Service-Wrapper. Was das genau ist und was ich mir bei der Singleton-Service Struktur gedacht habe kann ich gerne mal bei unserem ersten Code-Treffen (nach der Einführung) erläutern. Zielt auf Wartbarkeit und Skalierbarkeit des Studienführers ab :)

**Comment by jonas-l-b** [comment]
Im Branch passwordStrengthAndSecurity wird hier nun auch ein relativ starkes Passwort verlangt, damit die Änderung erfolgreich ist.

**Comment by jonas-l-b** [comment]
Ansonsten funktioniert es. Hab es mehrmals getestet.
