### ISSUE TITLE
Wie Modal über Menü aufrufen?

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#71]
@jonas-l-b , wie kann man ein Modal aufrufen, dessen Code in einer anderen Datei steht.
Ansatz:
![image](https://user-images.githubusercontent.com/30285755/29519310-4e94f29a-86c0-11e7-9570-36fab0518264.png)
Ergebnis:
![image](https://user-images.githubusercontent.com/30285755/29519386-99aecdfa-86c0-11e7-8447-b688b053a3a3.png)
Da stimmt noch was nicht! Aber ich weiß nicht so recht, was...

(Soll schon später über den Footer aufgerufen werden, aber so einfach hab ich den auch nicht hingekriegt..)

**Comment by jonas-l-b** [comment]
fixed

**Comment by jonas-l-b** [comment]
Btw: Inhaltliche Fehler müssen nicht nur Veranstaltungen betreffen. Der Fehler kann auch bei Modulen oder ähnlichem liegen ....
