### ISSUE TITLE
Bild für Benutzer; Standardbild, falls keines hochgeladen

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#72]

**Comment by jonas-l-b** [comment]
Wollen Leute wirklich ein Bild Hochladen? Lebt die Platform nicht ein wenig
von der Anonymität?

Am 22.08.2017 08:00 schrieb "juliangermek" <notifications@github.com>:

**Comment by juliangermek** [comment]
Ne, hast Recht, war sehr impulsiv, weil ich ne Inbox gesehen hab, die mit Bild hübsch aussah ;)
