### ISSUE TITLE
Benutzer-Menü funktioniert nicht immer

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#75]
Ist man schon im Benutzerprofil (userProfile.php) und klickt auf den Favouriten-Tab in der nav-bar (nicht im Profil selbst), ändert sich zwar die URL zu userProfile.php#favourites, man verbleibt aber im Profil-Tab.

**Comment by jonas-l-b** [comment]
gelöst
