### ISSUE TITLE
Super-Admins

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#78]
Super-Admins haben zusätzlich die Möglichkeit, Administratoren zu ernennen und diesen Status auch wieder zu löschen.
- Super-Admin-Bereich (Reiter in Admin-Menü)
- Weitere Spalte in Datenbank

**Comment by jonas-l-b** [comment]
Vielleicht kann man die Super-Admins einfach "Admins" nennen, und die anderen eventuell Moderatoren o.ä. 
Der normal ernannte "Admin" wird ja vermutlich selten mit etwas technischem konfrontiert werden. (Ist aber auch relativ egal wie mans nennt).

**Comment by juliangermek** [comment]
Für Super-Admin spräche, dass man den "Admin" überall so lassen kann wies ist :)

**Comment by jonas-l-b** [comment]
Stimmt. Keine unnötige Arbeit machen.
