### ISSUE TITLE
Kommentare sortieren: Danach wieder Kommentare anzeigen, nicht Seitenanfang

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#9]
Sortiert man die Kommentare auf der Veranstaltungsseite, wird die Seite neu geladen, sodass man wieder den Seitenanfang angezeigt bekommt. Besser wäre es, direkt wieder bei den Kommentaren rauszukommen.
Lösungsmöglichkeiten
- Anker verwenden (die Frage ist bloß: wie?)
- AJAX verwenden, sodass die Seite nicht neue geladen wird, sondern nur die Kommentare

**Comment by jonas-l-b** [comment]
Ajax wäre natürlich sexier 💃 aber anker geht schnell. 

Vorschlag: An den Reload Request (also an die URL) ein #comments anhängen. Dann der ganzen Kommentarbox das id-Attribut auf "comments" setzen. Fertig.

Ich mach mal PR.

**Comment by juliangermek** [comment]
Top :muscle:
Bei mir hat der irgendwie nicht so recht funktioniert...
