### ISSUE TITLE
Vorschlag: Levels 

### ISSUE THREAD

**Issue by jonas-l-b** [jonas-l-b/vwi_studienfuehrer#91]
Weiß nicht, was bei der Umfrage rausgekommen ist, aber wenn wir das Kernprogramm nicht mit reinnehmen, dann würde ich die Level später umtaufen in "Bachelooooor" und "Masteeeeeeer" mit adequater Menge E's und O's.
🔨

**Comment by juliangermek** [comment]
Die Umfrage ist leider nicht ganz so repräsentativ mit zwei Teilnehmern - und die meinen auch noch gegensätzliches... Aber ja, falls wir das so machen, macht das natürlich Sinn :ok_hand:

**Comment by jonas-l-b** [comment]
Für mich ist heißt das: ING-Teil vom Grundstudium kommt rein (da gibt's ja wahlmöglichkeiten), der Rest nicht. Diesen "Hinweis" kann man sich mal überleben ob der irgendwo sinnvoll hinpasst. IMHO
