### ISSUE TITLE
Logo in nav bar

### ISSUE THREAD

**Issue by juliangermek** [jonas-l-b/vwi_studienfuehrer#95]
Eigentlich würde sich das vwi logo ganz gut in der nav-bar machen, allerdings habe ich das damals nicht wirklich hinbekommen. Habe das eben nochmal probiert und es geht zwar von der Ansicht her, ist aber eher hässlich implementiert und ich weiß auch nicht, was passiert, wenn wir den Studienführer mal für kleine Bildschirme anpassen. Verbesserungsvorschläge als gerne gesehen!

Vorschlag als Branch "proposal-logo-in-nav".

**Comment by jonas-l-b** [comment]
Ich hab mich nochmal dran versucht, siehe branch.

**Comment by jonas-l-b** [comment]
Ich muss auch zugeben, der submenu effekt ist noch nicht ganz stilsicher...
